In [160]:
import numpy as np

#### Question


In [163]:
def vendermodePolyFill(arr, n, increasing=False):
    print("Theophile Vandermonde, No of columns:{}, increasing:{}, input array:{}".format(n, increasing, arr), "\n", "*"*80, sep="")
    new_array = np.zeros((arr.shape[0], n), dtype=arr.dtype.str)
    for i in range(n):
        elemWisePower = (n-i-1)
        index = elemWisePower if increasing else i
        ithOutputCol = arr ** elemWisePower
        new_array[:, index] = ithOutputCol
        #print("Element Wise Power: {}, {}th output col :{}".format(elemWisePower, i, ithOutputCol))
    return new_array

print(vendermodePolyFill(x, 7, True), "\n")
print(vendermodePolyFill(x, 4, False))

Theophile Vandermonde, No of columns:7, increasing:True, input array:[1 2 3 5]
********************************************************************************
[[    1     1     1     1     1     1     1]
 [    1     2     4     8    16    32    64]
 [    1     3     9    27    81   243   729]
 [    1     5    25   125   625  3125 15625]] 

Theophile Vandermonde, No of columns:4, increasing:False, input array:[1 2 3 5]
********************************************************************************
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


#### Question 
Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [168]:
def movingAverage(arr, k):
    print("Moving average for the array: {} with the window:{} ".format(arr, k), '\n', '*'*101, sep="")
    res = np.array([])
    size =arr.size
    seq = size-k+1
    for start in range(seq):
        end = start + k
        slicedItems = arr[start:end]
        movingAvgAtIndex = np.sum(slicedItems)/k
        print("start:{} end:{}, items:{}, average:{}".format(start, end, slicedItems, movingAvgAtIndex))
        res = np.append(res, movingAvgAtIndex)
    return res
l = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
movingAverage(l, 3)

Moving average for the array: [  3   5   7   2   8  10  11  65  72  81  99 100 150] with the window:3 
*****************************************************************************************************
start:0 end:3, items:[3 5 7], average:5.0
start:1 end:4, items:[5 7 2], average:4.666666666666667
start:2 end:5, items:[7 2 8], average:5.666666666666667
start:3 end:6, items:[ 2  8 10], average:6.666666666666667
start:4 end:7, items:[ 8 10 11], average:9.666666666666666
start:5 end:8, items:[10 11 65], average:28.666666666666668
start:6 end:9, items:[11 65 72], average:49.333333333333336
start:7 end:10, items:[65 72 81], average:72.66666666666667
start:8 end:11, items:[72 81 99], average:84.0
start:9 end:12, items:[ 81  99 100], average:93.33333333333333
start:10 end:13, items:[ 99 100 150], average:116.33333333333333


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])